### ISSUE TITLE
Issue pushing stable/beta to mainnet

### ISSUE THREAD

**Issue by ddorgan** [paritytech/push-release#19]
Seeing this error from the push release service:

```
0|push-rel | 2019-01-31 10:24 +00:00: Pushing commit: ec81d67009a9851ca4013bbf0d27a7e037c900b0 (tag: v2.2.8)
0|push-rel | 2019-01-31 10:24 +00:00: Track: stable => stable (1) [enabled: true]
0|push-rel | 2019-01-31 10:24 +00:00: On network ethereum
0|push-rel | 2019-01-31 10:24 +00:00: ethereum
0|push-rel | 2019-01-31 10:24 +00:00: TypeError: Cannot read property 'forkBlock' of undefined
0|push-rel |     at /root/push-release/server.js:104:47
0|push-rel |     at <anonymous>
0|push-rel |     at process._tickCallback (internal/process/next_tick.js:160:7)
0|push-rel | 2019-01-31 10:24 +00:00: TypeError: Cannot read property 'forkBlock' of undefined
0|push-rel |     at /root/push-release/server.js:104:47
0|push-rel |     at <anonymous>
0|push-rel |     at process._tickCallback (internal/process/next_tick.js:160:7)
0|push-rel | 2019-01-31 10:24 +00:00: Response Body:
0|push-rel | 2019-01-31 10:24 +00:00: Cannot read property 'forkBlock' of undefined
0|push-rel | Response: 500 271.242 ms - 45
```

**Comment by ddorgan** [comment]
Resolved with: https://github.com/paritytech/push-release/pull/20
